on:
  push:
    branches:
      - current
      - next
      - 'v*'
  pull_request:
    paths-ignore:
      - docs/**

name: CI

jobs:
  lint:
    permissions:
      contents: read
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: v22.x
          cache: 'npm'
          cache-dependency-path: package.json

      - name: Install dependencies
        run: npm install
      - name: Check linting
        run: npm run lint

  tests:
    permissions:
      contents: read
    name: Tests
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        node-version: [18.x, 20.x, 22.x]
    runs-on: ${{matrix.os}}
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: package.json

      - name: Install Dependencies
        run: npm install

      - name: Run Tests
        run: npm run test:ci

  automerge:
    if: >
      github.event_name == 'pull_request' && github.event.pull_request.user.login == 'dependabot[bot]'
    needs:
      - tests
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Merge Dependabot PR
        uses: fastify/github-action-merge-dependabot@c3bde0759d4f24db16f7b250b2122bc2df57e817 # v3.11.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
